# Generated by Django 5.2 on 2025-04-23 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration_no', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=100)),
                ('car_colour', models.CharField(max_length=50)),
                ('car_manufacturer', models.CharField(max_length=100)),
                ('departure_terminal', models.CharField(max_length=50)),
                ('return_terminal', models.CharField(max_length=50)),
                ('departure_flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('return_flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('total_passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_time', models.DateTimeField()),
                ('dropoff_time', models.DateTimeField()),
                ('pickup_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('add_ons', models.ManyToManyField(blank=True, to='services.addon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
