# Generated by Django 5.2 on 2025-04-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_price',
            new_name='total_price',
        ),
    ]
