# Generated by Django 5.2 on 2025-04-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_pickup_price_booking_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dropoff_time',
            new_name='return_time',
        ),
    ]
