# Generated by Django 5.2 on 2025-04-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_coupon_booking_discounted_price'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'booking'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
    ]
