# Generated by Django 5.2 on 2025-05-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='surname',
            new_name='last_name',
        ),
    ]
