# Generated by Django 5.2 on 2025-05-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_surname_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
