# Generated by Django 5.2 on 2025-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_coupon_awarded',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
