# Generated by Django 5.2 on 2025-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_discount_coupon_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
