# Generated by Django 5.2 on 2025-05-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_note_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
