# Generated by Django 5.2 on 2025-05-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
