# Generated by Django 5.2 on 2025-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bonus_points_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
