# Generated by Django 5.2 on 2025-06-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_bonus_points_used'),
        ('bookings', '0017_bookinguser'),
    ]

    operations = [
    ]
