# Generated by Django 5.2 on 2025-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_merge_0017_booking_bonus_points_used_0017_bookinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_email_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='started_status_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
