# Generated by Django 5.2 on 2025-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_completion_email_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
