# Generated by Django 5.2 on 2025-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_booking_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='website',
            field=models.CharField(default='rsexpressparking', help_text='Source website for this booking', max_length=50),
        ),
    ]
