# Generated by Django 5.2 on 2026-02-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_booking_website'),
        ('users', '0004_customuser_is_supplier_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='If set, this booking was created by a vendor/supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.supplier'),
        ),
    ]
