# Generated by Django 5.2 on 2026-05-09 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='supplier_extended_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text='Admin-only extra amount for supplier bookings. This amount goes fully to RS.',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
