# Generated by Django 5.2 on 2026-05-09 10:02

from django.db import migrations, models


def backfill_supplier_commission(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    db_alias = schema_editor.connection.alias

    bookings = (
        Booking.objects.using(db_alias)
        .filter(supplier__isnull=False, supplier_commission_percentage__isnull=True)
        .select_related('supplier')
    )

    for booking in bookings.iterator(chunk_size=500):
        booking.supplier_commission_percentage = booking.supplier.commission_percentage
        booking.save(update_fields=['supplier_commission_percentage'], using=db_alias)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='supplier_commission_percentage',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text='Commission percentage snapshot saved at booking time for supplier payouts.',
                max_digits=5,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_supplier_commission, noop_reverse),
    ]
