# Generated by Django 5.2 on 2026-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=5),
        ),
    ]
