# Generated by Django 5.2 on 2026-04-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publish', 'Publish')], default='draft', max_length=10),
        ),
    ]
