# Generated by Django 5.2 on 2025-05-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_coupon_user_coupon_max_uses_coupon_times_used'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addon',
            table='addons',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupon',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
