# Generated by Django 5.2 on 2025-08-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.CharField(choices=[('both', 'Both'), ('rsexpressparking', 'RS Express Parking'), ('dublinairportparking', 'Dublin Airport Parking')], default='both', help_text='Which website(s) this service should appear on', max_length=32),
        ),
    ]
