# Generated by Django 5.2 on 2025-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='website',
            field=models.CharField(choices=[('both', 'Both'), ('rsexpressparking', 'RS Express Parking'), ('dublinairportparking', 'Dublin Airport Parking'), ('none', 'None')], default='both', help_text='Which website(s) this service should appear on', max_length=32),
        ),
    ]
