# Generated by Django 5.2 on 2025-11-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='lifetime',
            field=models.BooleanField(default=False, help_text='If checked, coupon never expires by date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='Leave blank if lifetime', null=True),
        ),
    ]
