# Generated by Django 5.2 on 2026-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_coupon_lifetime_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order total required to use this coupon. Set to 0 for no minimum.', max_digits=8),
        ),
    ]
