# Generated by Django 5.2 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_coupon_minimum_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this add-on'),
        ),
    ]
