# Generated by Django 5.2 on 2025-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='website',
            field=models.CharField(default='rsexpressparking', help_text='Source website for this contact message', max_length=50),
        ),
    ]
