# Generated by Django 5.2 on 2025-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='for_month',
            field=models.DateField(blank=True, help_text='The month this applies to (YYYY-MM-01 format)', null=True),
        ),
    ]
