# Generated by Django 5.2 on 2025-07-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_for_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring_end_month',
            field=models.DateField(blank=True, help_text='Recurring end month (YYYY-MM-01)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_start_month',
            field=models.DateField(blank=True, help_text='Recurring start month (YYYY-MM-01)', null=True),
        ),
    ]
