# Generated by Django 5.2 on 2025-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_recurring_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='website',
            field=models.CharField(choices=[('rsexpressparking', 'RS Express Parking'), ('dublinairportparking', 'Dublin Airport Parking'), ('both', 'Both')], default='both', max_length=32),
        ),
    ]
