# Generated by Django 5.2 on 2025-08-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='website',
            field=models.CharField(choices=[('rsexpressparking', 'RS Express Parking'), ('dublinairportparking', 'Dublin Airport Parking'), ('both', 'Both')], default='rsexpressparking', max_length=32),
        ),
    ]
