# Generated by Django 5.2 on 2026-05-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expense_website'),
        ('users', '0005_supplier_website_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.supplier')),
            ],
            options={
                'db_table': 'supplier_invoice',
                'unique_together': {('supplier', 'period_month', 'period_year')},
            },
        ),
    ]
