# Generated by Django 5.2 on 2025-04-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'payment'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
    ]
