# Generated by Django 5.2 on 2025-05-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
