# Generated by Django 5.2 on 2025-06-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
