# Generated by Django 5.2 on 2025-05-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
        migrations.AlterModelTable(
            name='faqcategory',
            table='faqcategory',
        ),
    ]
