# Generated by Django 5.2 on 2026-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_table_alter_faqcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='dynamic_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('services_pricing', 'Services Pricing')], default='', help_text='Type of dynamic content to generate for this FAQ', max_length=50),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_dynamic',
            field=models.BooleanField(default=False, help_text='If checked, the answer will be generated dynamically based on dynamic type'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(help_text='Static answer (used as fallback if dynamic is enabled)'),
        ),
    ]
