# Generated by Django 5.2 on 2026-02-08 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor business name', max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_id_prefix', models.CharField(help_text="Prefix used for booking IDs of this vendor's bookings (e.g., 'VN')", max_length=10, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage the supplier earns (we keep the rest)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Auto-created user account for this vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
