# Generated by Django 5.2 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_supplier_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, help_text='Vendor website URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
