# Generated by Django 5.2 on 2026-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_website_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='use_custom_booking_ids',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, supplier must provide a custom booking ID per booking. If disabled, IDs are auto-generated from prefix.',
            ),
        ),
    ]
