# Generated by Django 5.2 on 2025-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment')], max_length=20)),
            ],
            options={
                'db_table': 'Status',
                'unique_together': {('name', 'type')},
            },
        ),
    ]
