# Generated by Django 5.2 on 2025-06-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_status_table'),
        ('services', '0006_alter_addon_table_alter_coupon_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours_before_booking', models.PositiveIntegerField(default=4, help_text='Minimum hours before drop-off allowed for booking')),
            ],
            options={
                'db_table': 'booking_settings',
            },
        ),
        migrations.CreateModel(
            name='OrderLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_orders', models.IntegerField(blank=True, help_text='Max orders for this date/service. Null or -1 means unlimited.', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_limits', to='services.service')),
            ],
            options={
                'db_table': 'order_limit',
                'unique_together': {('date', 'service')},
            },
        ),
    ]
