# Generated by Django 5.2 on 2025-06-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookingsettings_orderlimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsettings',
            options={'verbose_name': 'Booking Settings', 'verbose_name_plural': 'Booking Settings'},
        ),
    ]
