# Generated by Django 5.2 on 2025-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bookingsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='manager_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of manager emails to notify for bookings'),
        ),
    ]
