# Generated by Django 5.2 on 2025-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bookingsettings_manager_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='promotional_email_content',
            field=models.TextField(blank=True, help_text='Content for promotional emails sent to users'),
        ),
    ]
