# Generated by Django 5.2 on 2025-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookingsettings_promotional_email_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='pending_bookings_email_content',
            field=models.TextField(blank=True, help_text='Content for promotional emails sent to users with pending bookings'),
        ),
    ]
