# Generated by Django 5.2 on 2025-08-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bookingsettings_pending_bookings_email_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='dublin_manager_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of manager emails to notify for Dublin Airport Parking bookings'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='manager_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of manager emails to notify for RS Express bookings'),
        ),
    ]
