# Generated by Django 5.2 on 2025-08-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookingsettings_dublin_manager_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='dublin_pending_bookings_email_content',
            field=models.TextField(blank=True, help_text='Content for promotional emails sent to Dublin Airport Parking users with pending bookings'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='dublin_promotional_email_content',
            field=models.TextField(blank=True, help_text='Content for promotional emails sent to Dublin Airport Parking users'),
        ),
    ]
