# Generated by Django 5.2 on 2025-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bookingsettings_dublin_pending_bookings_email_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unsubscribed_email',
            },
        ),
    ]
