# Generated by Django 5.2 on 2025-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_unsubscribedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('discount_code', models.CharField(blank=True, max_length=30)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketing_lead',
            },
        ),
    ]
