# Generated by Django 5.2 on 2026-01-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_marketinglead'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='social_media_email_content',
            field=models.TextField(blank=True, help_text='Content for monthly social media follow emails (RS Express only)'),
        ),
    ]
